main: SSM.SSM
name: Super_Smash_Mobs_2
version: 1
author: Whoneedspacee, SirInHueman, Huxs
description: 'An open source recreation of Super Smash Mobs'
api-version: 1.16
commands:
  kit:
    description: 'Applies the kit of the name entered'
    usage: /kit
  damage:
    description: 'Inflicts the damage proposed'
    usage: /damage number
  setspeed:
    description: 'Sets the base speed of the player'
    usage: /setspeed number
  jump:
    description: 'Does a jump'
    usage: /jump
  move:
    description: 'Does a move'
    usage: /move