main: SSM.SSM
name: Super_Smash_Mobs_2
version: 1
author: Heartlessknights, Whoneedspacee, Huxs
description: 'An open source recreation of Super Smash Mobs'
api-version: 1.15
commands:
  kit:
    description: 'Applies the kit of the name entered'
    usage: /kit
  damage:
    description: 'Inflicts the damage proposed'
    usage: /damage number
  rank:
    description: 'Gives you a rank'
    usage: /rank rank