main: ssm.Main
name: SSMOS
version: 1
author: Whoneedspacee, Deidara, YaBoiTim
description: 'An open source recreation of Super Smash Mobs'
api-version: 1.16
commands:
  kit:
    description: 'Applies the kit of the name entered'
    usage: /kit
  vote:
    description: 'Opens the voting menu'
    usage: /vote
  damage:
    description: 'Inflicts the damage proposed'
    usage: /damage number
  setspeed:
    description: 'Sets the base speed of the player'
    usage: /setspeed number
  jump:
    description: 'Does a jump'
    usage: /jump
  move:
    description: 'Does a move'
    usage: /move
  start:
    description: 'Starts the game.'
    usage: /start
  stop:
    description: 'Stops the game.'
    usage: /stop
  getstate:
    description: 'Gets the state of the game.'
    usage: /getstate
  tpworld:
    description: 'Teleports you to the provided world name.'
    usage: /tpworld world
  getloadedworlds:
    description: 'Prints a list of loaded worlds.'
    usage: /getloadedworlds
  loadworld:
    description: 'Loads the world specified.'
    usage: /loadworld world
  unloadworld:
    description: 'Unloads the world specified.'
    usage: /unloadworld world
  spectate:
    description: 'Toggles whether the player is spectating or not.'
    usage: /spectate
    aliases: [spec]
  setplaying:
    description: 'Forces a kits abilities to be active.'
    usage: /setplaying
  setgamemode:
    description: 'Sets the current gamemode.'
    usage: /setgamemode
  randomkit:
    description: 'Sets your kit randomly.'
    usage: /randomkit
  playerdisguise:
    description: 'Creates a player disguise using the skin of the name given.'
    usage: /playerdisguise
  damagelog:
    description: 'Shows a report of damage taken in the last 15 seconds.'
    usage: /damagelog
  setlives:
    description: 'Sets the lives of the player given to the number given.'
    usage: /setlives player number
  setkit:
    description: 'Sets the kit of the player given by name.'
    usage: /setkit player name
  loadgamemodeworld:
    description: 'Loads the base gamemode world specified to be edited.'
    usage: /loadgamemodeworld